remote_theme: raviriley/agency-jekyll-theme

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Bitcoin HashHouse
email      : bitcoinhashhouse@gmail.com #this is also the email contact forms will go to
description: "Peer to peer system of temporary and long-term housing for bitcoiners"
author     : Your Name

locale: "en-US" # See available languages in _data/sitetext.yml

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme